apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-webapp
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webapp.service.type }}
  ports:
    - port: {{ .Values.webapp.service.port }}
      targetPort: http
      nodePort: {{ .Values.webapp.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    type: webapp
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-apiserver
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiserver.service.type }}
  ports:
    - port: {{ .Values.apiserver.service.port }}
      targetPort: http
      nodePort: {{ .Values.apiserver.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
    type: apiserver