name: Build Docker Images
on:
  push:
    tags:
      - '*'
jobs:
  build-webapp:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: cd frontend
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
    - run: npm run build
    - name: Build and Push Docker Image With Version
      uses: docker/build-push-action@v3
      with:
        push: true
        context: .
        tags: bench352/prior2do-webapp:latest
    - name: Build and Push Latest Docker Image
      uses: docker/build-push-action@v3
      with:
        push: true
        context: .
        tags: bench352/prior2do-webapp:${{ github.ref_name }}
  build-syncserver:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: cd backend
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and Push Docker Image With Version
      uses: docker/build-push-action@v3
      with:
        push: true
        context: .
        tags: bench352/prior2do-syncserver:latest
    - name: Build and Push Latest Docker Image
      uses: docker/build-push-action@v3
      with:
        push: true
        context: .
        tags: bench352/prior2do-syncserver:${{ github.ref_name }}
