name: Publish To GitHub Pages
on:
  push:
    tags:
      - '*'
jobs:
  publish-to-github-pages:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
    - run: sed -i '3i "homepage": "https://bench352.github.io/prior2do/",' package.json
    - run: npm run deploy
