name: Update Helm Repo
on:
  push:
    tags:
      - '*'
jobs:
  update-helm-repo:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./deployment
    steps:
    - uses: actions/checkout@v2
    - name: Helm tool installer
      uses: Azure/setup-helm@v3
    - run: helm package chart --version ${{ github.ref_name }} --destination helm-repo
    - run: helm repo index helm-repo
    - name: Commit And Push Changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update Helm Repository"
        git push
